//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsComment
    {
        public System.Guid ID { get; set; }
        public string sCommentContent { get; set; }
        public string sGoodNo { get; set; }
        public System.DateTime dCommentTime { get; set; }
        public string sCommentPerson { get; set; }
    }
}
