//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
    

        public virtual int Proc_PageQuery(string sTableName, Nullable<int> page, Nullable<int> rows, string sSelectFields, string sOrderField, string sOrder, string sWhereFields)
        {
            var sTableNameParameter = sTableName != null ?
                new ObjectParameter("sTableName", sTableName) :
                new ObjectParameter("sTableName", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("rows", rows) :
                new ObjectParameter("rows", typeof(int));
    
            var sSelectFieldsParameter = sSelectFields != null ?
                new ObjectParameter("sSelectFields", sSelectFields) :
                new ObjectParameter("sSelectFields", typeof(string));
    
            var sOrderFieldParameter = sOrderField != null ?
                new ObjectParameter("sOrderField", sOrderField) :
                new ObjectParameter("sOrderField", typeof(string));
    
            var sOrderParameter = sOrder != null ?
                new ObjectParameter("sOrder", sOrder) :
                new ObjectParameter("sOrder", typeof(string));
    
            var sWhereFieldsParameter = sWhereFields != null ?
                new ObjectParameter("sWhereFields", sWhereFields) :
                new ObjectParameter("sWhereFields", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_PageQuery", sTableNameParameter, pageParameter, rowsParameter, sSelectFieldsParameter, sOrderFieldParameter, sOrderParameter, sWhereFieldsParameter);
        }
    }
}
